env:
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - prettier

plugins:
  - import
  - unused-imports
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"
parserOptions:
  tsconfigRootDir: .

settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: "./tsconfig.json"

ignorePatterns:
  - "*.d.ts"

rules:
  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-non-null-assertion": off
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars:
    - warn
    - vars: all
      varsIgnorePattern: ^_
      args: all
      argsIgnorePattern: ^_
  import/order:
    - error
    - alphabetize:
        order: asc
      groups:
        - - type
        - - builtin
          - external
        - - parent
          - sibling
          - index
        - - object
      newlines-between: always-and-inside-groups
