name: Build

on:    
  push:
    branches:
      - master
    paths:
      - "modules/*/*.ts"
      - "modules/*/package.json"
      - "yarn.lock"
      - ".github/*"

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        uses: ./.github/actions/build 
